version: "3.8"

networks:
  lwnet:
    driver: bridge

volumes:
  myvol:

services:
  db:
    image: mysql:latest
    container_name: mydb1
    networks:
      - lwnet
    volumes:
      - myvol:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=redhat
      - MYSQL_DATABASE=mydb
      - MYSQL_USER=kabali
      - MYSQL_PASSWORD=redhat
  
  wp:
    image: wordpress:latest
    container_name: mywp1
    networks:
      - lwnet
    ports:
      - 8080:80
    depends_on:
      - db
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_NAME=mydb
      - WORDPRESS_DB_USER=kabali
      - WORDPRESS_DB_PASSWORD=redhat
      - WORDPRESS_TABLE_PREFIX=wp_
      - WORDPRESS_DEBUG=1
